let user = {
  // name: "‫אריאל לוh",
  // gender: "זכר",
  // date_of_birth: "2023-04-25",
  // email: "ariellevi19981998@gmail.com",
  // phone: "0549227119",
  // height: "150",
  // yishuv: "פתח תקווה",
  // region: "צפון",
  // type_of_residence: "גר עם ההורים",
  // family_status: "רווק",
  // there_are_children: "כן",
  // current_occupation: "עובד",
  // religious_level: "חרדי",
  // body_structure: "רזה",
  // ethnicity: "אשכנז",
  // national_or_military_service: "שירות לאומי",
  // details: "",
  // education: "תיכונית",
  // educational_framework: "רגילה",
  // about_my_family: "",
  // disability_Physical: false,
  // disability_intellectual: false,
  // disability_developmental: false,
  // disability_mentally_challenged: false,
  // type_of_disability_info: "",
  // independent_disability: "כן",
  // interest: "",
  // standing_out_features: "",
  // hobbys: "",
  // age_min: "18",
  // age_max: "120",
  // in_terms_of_character: "",
  // religiously: "",
  // in_terms_of_appearance: "",
  // seek_for_disability_doesnt_matter: false,
  // seek_for_disability_Physical: false,
  // seek_for_disability_intellectual: false,
  // seek_for_disability_developmental: false,
  // seek_for_disability_mentally_challenged: false,
  // seek_for_type_of_disability_info: "",
  // questions_on_your_own: "כן",
  // additional_notes: "",
  // contact_name: "‫אריאל לוי‬‎",
  // contact_phone: "0549227119",
  // contact_family_relationship: "זה אני",
  // img_url:"https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__340.png",
};
